---
driver:
  name: vagrant
  network:
    - [ "forwarded_port", { guest: 80, host: 8080, auto_correct: true } ]

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[racktables::default]
