---
driver:
  name: vagrant
  network:
    - [ "forwarded_port", { guest: 80, host: 8080, auto_correct: true } ]

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[racktables::default]
    attributes:
      mysql:
        server_root_password: rootpass
        server_debian_password: debpass
        server_repl_password: replpass
  - name: ldap
    run_list:
      - recipe[racktables::ldap]
