---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver:
      box: osuosl-centos-6.5
      box_url: http://vagrant.osuosl.org/centos-6-20140121.box

suites:
  - name: default
    run_list:
      - recipe[mysql::server]
      - recipe[racktables::default]
    attributes:
      mysql:
        server_root_password: rootpass
        server_debian_password: debpass
        server_repl_password: replpass
      racktables:
        ssl_enabled: false
        redirect_http: false
