---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

driver_config:
    require_chef_omnibus: true

provisioner: chef_solo

platforms:
  - name: centos-65

suites:
  - name: default
    run_list:
      - recipe[racktables::default]
    attributes:
      mysql:
        server_root_password: rootpass
        server_debian_password: debpass
        server_repl_password: replpass
      racktables:
        ssl_enabled: false
        redirect_http: false
